name: Fetch Latest Blog from Dev.to

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  fetch-latest-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use Node.js version 16 or your desired version

      - name: Install dependencies
        run: |
          npm install

      - name: Fetch latest blog post from Dev.to
        run: |
          curl -H "api-key: ${{ secrets.DEVTO_API_KEY }}" \
            "https://dev.to/api/articles?username=${{ secrets.DEVTO_USERNAME }}&per_page=1" \
            > latest_blog.json

      - name: Process blog post and add to repository
        run: |
          # Extract blog details from the JSON response and format them for your site
          BLOG_TITLE=$(jq -r '.[0].title' latest_blog.json)
          BLOG_CONTENT=$(jq -r '.[0].body_markdown' latest_blog.json)
          BLOG_DATE=$(jq -r '.[0].created_at' latest_blog.json)

          # Create a markdown file for the blog post
          echo "# $BLOG_TITLE" > content/latest-blog.md
          echo "Date: $BLOG_DATE" >> content/latest-blog.md
          echo "$BLOG_CONTENT" >> content/latest-blog.md

      - name: Commit and push new blog post
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add content/latest-blog.md
          git commit -m "Add latest blog post from Dev.to"
          git push origin main
