name: Fetch Latest Blog from Dev.to

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  fetch-latest-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use Node.js version 16 or your desired version

      - name: List repository
        run: |
          ls -la

      - name: Install npm
        run: npm init && npm install
